// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const borderWidths = {
 "$border-width-none": "0px",
 "$border-width-hairline": "1px",
 "$border-width-thin": "2px",
 "$border-width-thick": "4px",
 "$border-width-heavy": "8px"
}

export default borderWidths;