// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const borderRadius = {
 "$border-radius-none": "0px",
 "$border-radius-sm": "3px",
 "$border-radius-md": "8px",
 "$border-radius-lg": "16px",
 "$border-radius-pill": "500px",
 "$border-radius-circular": "100px"
}

export default borderRadius;