// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const borderWidths = {
 "Chunky": "8px",
 "Fat": "4px",
 "Regular": "2px",
 "Hairline": "1px"
}

export default borderWidths;