// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "$color-grey-200": "rgba(246, 246, 246, 1)",
 "$color-grey-100": "rgba(250, 250, 250, 1)",
 "$color-grey-700": "rgba(66, 66, 66, 1)",
 "$color-grey-300": "rgba(189, 189, 189, 1)",
 "$color-grey-600": "rgba(97, 97, 97, 1)",
 "$color-grey-400": "rgba(119, 120, 122, 1)",
 "$color-grey-800": "rgba(25, 25, 26, 1)",
 "$color-grey-500": "rgba(117, 117, 117, 1)",
 "$color-blue-200": "rgba(41, 121, 255, 0.5)",
 "$color-blue-100": "rgba(215, 227, 246, 1)",
 "$color-green-200": "rgba(0, 230, 118, 0.5)",
 "$color-green-100": "rgba(213, 245, 215, 1)",
 "$color-purple-400": "rgba(94, 53, 177, 1)",
 "$color-purple-300": "rgba(103, 58, 183, 0.5)",
 "$color-purple-200": "rgba(124, 77, 255, 1)",
 "$color-purple-100": "rgba(231, 219, 255, 1)",
 "$color-yellow-300": "rgba(255, 213, 79, 1)",
 "$color-yellow-200": "rgba(255, 193, 7, 0.5)",
 "$color-yellow-100": "rgba(255, 236, 179, 1)",
 "$color-red-400": "rgba(244, 81, 30, 1)",
 "$color-red-300": "rgba(240, 61, 62, 0.5)",
 "$color-red-200": "rgba(240, 61, 62, 1)",
 "$color-red-100": "rgba(251, 233, 231, 1)",
 "$color-bg-400": "rgba(66, 66, 66, 1)",
 "$color-bg-300": "rgba(29, 30, 31, 1)",
 "$color-bg-200": "rgba(26, 27, 28, 1)",
 "$color-bg-100": "rgba(23, 24, 25, 1)",
 "$color-bg-000": "rgba(255, 255, 255, 1)"
}

export default colors;