// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const durations = {
 "Very long": 1,
 "Long": 0.6,
 "Medium": 0.25,
 "Short": 0.15
}

export default durations;