// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

enum fontSizes {
  '$font-size-xxxxs' = '0.625rem',
  '$font-size-xxxs' = '0.75rem',
  '$font-size-xxs' = '0.875rem',
  '$font-size-xs' = '1rem',
  '$font-size-sm' = '1.25rem',
  '$font-size-md' = '1.5rem',
  '$font-size-lg' = '2rem',
  '$font-size-xl' = '2.25rem',
  '$font-size-xxl' = '2.625rem',
  '$font-size-xxxl' = '3rem',
}

export default fontSizes;