// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

enum fontWeights {
  '$font-weight-regular' = '400',
  '$font-weight-medium' = '600',
  '$font-weight-bold' = '400',
}

export default fontWeights;