// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "$font-size-xxxl": "3rem",
 "$font-size-xxl": "2.625rem",
 "$font-size-xl": "2.25rem",
 "$font-size-lg": "2rem",
 "$font-size-md": "1.75rem",
 "$font-size-sm": "1.375rem",
 "$font-size-xs": "0.875rem",
 "$font-size-xxs": "0.875rem",
 "$font-size-xxxs": "0.75rem",
 "$font-size-xxxxs": "0.625rem"
}

export default fontSizes;