// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontWeights = {
 "$font-weight-bold": 700,
 "$font-weight-medium": 600,
 "$font-weight-regular": 400,
 "$font-weight-light": 300
}

export default fontWeights;