// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const letterSpacings = {
 "Tight": "-0.045em",
 "Wide": "0.05em",
 "Regular": "0em"
}

export default letterSpacings;