// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

enum lineHeights {
  '$line-height-lg' = '1.65',
  '$line-height-md' = '1.65',
  '$line-height-sm' = '1.65',
}

export default lineHeights;