// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const lineHeights = {
 "$line-height-xs": "1.00",
 "$line-height-sm": "1.25",
 "$line-height-md": "1.45",
 "$line-height-lg": "1.65"
}

export default lineHeights;