// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const mediaQueries = {
 "MobileSm": "320px",
 "MobileMd": "480px",
 "MobileLg": "580px",
 "MobileMax": "767px",
 "TabletMin": "768px",
 "TabletMax": "1024px",
 "DesktopMd": "1180px",
 "DesktopLg": "1440px",
 "Wide": "1920px"
}

export default mediaQueries;