// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const opacities = {
 "Opaque": 1,
 "Disabled": 0.65,
 "Semi Opaque": 0.5,
 "Transparent": 0
}

export default opacities;