// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const radii = {
 "$border-radius-full": "100px",
 "$border-radius-xxs": "2px",
 "$border-radius-xs": "3px",
 "$border-radius-xxxs": "1px",
 "$border-radius-0": "0px"
}

export default radii;