// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const shadows = {
 "Deep": "3px 3px 3px rgba(196, 196, 196, 0.75)",
 "Medium": "0px 0px 5px rgba(0, 0, 0, 0.5)",
 "Soft": "0px 0px 5px rgba(196, 196, 196, 1)"
}

export default shadows;