// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacingStack = {
 "$spacing-stack-quarck": "0.25rem",
 "$spacing-stack-nano": "0.5rem",
 "$spacing-stack-xxxs": "1rem",
 "$spacing-stack-xxs": "1.5rem",
 "$spacing-stack-xs": "2rem",
 "$spacing-stack-sm": "2.5rem",
 "$spacing-stack-md": "3rem",
 "$spacing-stack-lg": "3.5rem",
 "$spacing-stack-xl": "4rem",
 "$spacing-stack-xxl": "5rem",
 "$spacing-stack-xxxl": "7.5rem",
 "$spacing-stack-huge": "10rem",
 "$spacing-stack-giant": "12.5rem"
}

export default spacingStack;