// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "$spacing-xxl": "3rem",
 "$spacing-xl": "2.5rem",
 "$spacing-lg": "2rem",
 "$spacing-md": "1.5rem",
 "$spacing-sm": "1rem",
 "$spacing-xs": "0.5rem",
 "$spacing-xxs": "0.25rem"
}

export default spacing;