// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "$spacing-xxl": "6rem",
 "$spacing-xl": "4rem",
 "$spacing-lg": "3rem",
 "$spacing-md": "1rem",
 "$spacing-sm": "0.75rem",
 "$spacing-xs": "0.5rem",
 "$spacing-xxs": "0.25rem"
}

export default spacing;