// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

enum spacingInline {
  '$spacing-inline-quarck' = '0.25rem',
  '$spacing-inline-nano' = '0.5rem',
  '$spacing-inline-xxxs' = '1rem',
  '$spacing-inline-xxs' = '1.5rem',
  '$spacing-inline-xs' = '2rem',
  '$spacing-inline-sm' = '2.5rem',
  '$spacing-inline-md' = '3rem',
  '$spacing-inline-xl' = '4rem',
  '$spacing-inline-xxl' = '5rem',
}

export default spacingInline;