// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const zIndices = {
 "Top": 100,
 "Focus": 10,
 "Higher": 2,
 "High": 1,
 "Regular": 0
}

export default zIndices;